### ISSUE TITLE
neo4j-backup 5.x

### ISSUE THREAD

**Issue by ybshr** [andreshyer/neo4j-backup#12] opened 2023-03-14 20:11 UTC
**Hello** 
I hope you are well 
I used this package  for making a dump in **neo4j 5.x** and I noticed the package is not compatible with **neo4j 5.x** since the format of the **constraint** changed in **neo4j 5.x**  so I made an update for  the package  

I made Fork and push an update 
I hope to see it and make some improvements from your perspective

**Comment by andreshyer** [comment] 2023-03-14 21:10
Would you be willing to share the error message that you get when trying to use the tool in a neo4j 5.x database? I believe there should be support for the new constraint format in 5.x databases. 

Currently there is only support for Unique node property constraints, since those are the only constraints that are available both in the community and enterprise editions.

**Comment by ybshr** [comment] 2023-03-14 22:43
absolutely ,
the new update not extract anything just keep the code running and bar for
tqdm package not seen
also ""call db.constraints"" not available in neo4j 5.x  the format for
result changed also apply constraints query change a little bit[image:
Screenshot from 2023-03-15 00-36-07.png]
[image: Screenshot from 2023-03-15 00-35-38.png]

**Comment by ybshr** [comment] 2023-03-16 20:39
Hello Dear ,
I hope you are doing well
Do you realize the problem ?
I want to let you know that I'm available to help you advance my knowledge
with you

Sincerely,
Younis

**Comment by andreshyer** [comment] 2023-03-17 14:04
Sorry for the late response, I had to take a couple of exams for school. 

But, I have been trying to reproduce the problem you have described, and I am unable to. I do not see the images that you attached. I see you responded using email, I believe that may be the issue. Would you be willing to reply directly in GitHub and reattach the images? Also, what version of neo4j-backup are you using?

The way I am testing the neo4j-backup tool is (Beside test scripts in source code)

1. Using Neo4j Desktop
2. Start new 5.X database (I am using 5.2)
3. Run the query `:play movies`, and run create statements. This is to make a dummy database.
4. Then I am creating a contraint `CREATE CONSTRAINT FOR (n:Person) REQUIRE n.node_id IS UNIQUE`
5. Then while the database is running, run the extract script using the neo4j-backup tool

After taking the above steps, in the data dump folder in the `uniqueness_constraints.json`, the following data exist

```
[
    {
        "node_label": "Person",
        "node_prop": "node_id",
        "constraint_name": "constraint_29f093cb"
    }
]
```

If you are willing to, would you be able to do the above steps as well, and see if you get the same output?

**Comment by ybshr** [comment] 2023-03-18 15:12
### Sorry for being confused, it seems you have updated the package thank you vary much!

Sorry for the late response, 

- when I `CALL db.constraints()` I got this error  

`Neo.ClientError.Procedure.ProcedureNotFound
There is no procedure with the name `db.constraints` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`
it seems is not available in neo4j 5.x 
 keep in mind I used a docker container  and your code extraction dump based on `CALL db.constraints()` 

- SHOW constraints 
`

id | name | type | entityType | labelsOrTypes | properties | ownedIndex
-- | -- | -- | -- | -- | -- | --
1 | 4 | "Movie_id" | "UNIQUENESS" | "NODE" | ["Movie"] | ["id"] | "Movie_id"
2 | 6 | "constraint_29f093cb" | "UNIQUENESS" | "NODE" | ["Person"] | ["node_id"] | "constraint_29f093cb"

`
there's no description and your importer code based on the description 

you can test that using this code from neo4j docs 
`docker run \
    --restart always \
    --publish=7474:7474 --publish=7687:7687 \
    --env NEO4J_AUTH=neo4j/your_password \
    neo4j:5.2.0`

**Comment by andreshyer** [comment] 2023-03-18 17:31
I truly do appreciate your time and trying to help. I am glad that the updated package was able to work for you! I am going to close this thread, but I do want to give details about how the constraints are handled just for other people in the future.

 In the `src/neo4j_backup/neo4j_extractor.py` in lines 161-178

```python
    def _pull_constraints(self):

        with self.driver.session(database=self.database) as session:

            # Older verisons
            try:
                results = session.run("CALL db.constraints")
                for result in results:

                    # Get raw constraint string
                    constraint_description = dict(result)['description']

                    # Verify is uniqueness constraint
                    if "unique" in constraint_description:
                        # Get the node label
                        node_label = constraint_description.split(":")[1]
                        node_label = node_label.split(")")[0].strip()

                        # Get the node property
                        node_prop = constraint_description.split(".")[1]
                        node_prop = node_prop.split(")")[0].strip()

                        constraint_name = dict(result)['name']
                        constraint = dict(
                            node_label=node_label,
                            node_prop=node_prop,
                            constraint_name=constraint_name,
                        )
                        self.uniqueness_constraints.append(constraint)
                        self.uniqueness_constraints_names.append(constraint_name)

            # Newer verisons
            except:
                results = session.run("SHOW CONSTRAINTS")
                for result in results:
                    if result["type"] == "UNIQUENESS" and result["entityType"] == "NODE":
                        constraint_name = result["name"]
                        for node_label in result["labelsOrTypes"]:
                            for node_prop in result["properties"]:
                                constraint = dict(
                                    node_label=node_label,
                                    node_prop=node_prop,
                                    constraint_name=constraint_name,
                                )
                                self.uniqueness_constraints.append(constraint)
                                self.uniqueness_constraints_names.append(constraint_name)
```

This ensures that the constraints for both Neo4j 4.x and Neo4j 5.x are stored the same. Then when the constraints get imported, the following in `src/neo4j_backup/neo4j_importer.py` in lines 109-125

```python
    @staticmethod
    def _apply_constraint(session, constraint):
        try:
            constraint_str = f"""
            CREATE CONSTRAINT {constraint['constraint_name']} 
            FOR (n:{constraint['node_label']}) 
            REQUIRE n.{constraint['node_prop']} IS UNIQUE
            """
            session.run(constraint_str)
            return
        except:
            constraint_str = f"""
            CREATE CONSTRAINT {constraint['constraint_name']} 
            ON (n:{constraint['node_label']}) 
            ASSERT n.{constraint['node_prop']} IS UNIQUE
            """
            session.run(constraint_str)
```

**Closed as completed** 2023-03-18 17:31 UTC
Labels: question
